name: React

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          dry-run: true
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/checkout@v4
        with:
          node-version: '20.x'
          
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

  upload:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact 'build'
        uses: actions/download-artifact@master
        with:
          name: 'build'
          path: '${{ github.workspace }}/build' 
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: build/
          server-dir: public_nodejs/
          git-ftp-args: '--all'
