name: React

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
  build:
    runs-on: windows-latest

    steps:
      - name: Setup Node
        uses: actions/checkout@v3
        with:
          node-version: '20.x'
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ./public_nodejs/
