name: React

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ./public_nodejs/
          dry-run: true
        
  build:
    if: success()
    runs-on: windows-latest
    steps:
      - name: Setup Node
        uses: actions/checkout@v3
        with:
          node-version: '20.x'
          
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
          
  production-deploy:
    if: success()
    runs-on: windows-latest
    steps:
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ./public_nodejs/
